### ISSUE TITLE
The much needed, "Start Speaking", or rather "Dictate... from here" still missing.

### ISSUE THREAD

**Issue by mralexgray** [Nosrac/Dictater#7]
My longest–lived and most irksome problem with the absence of a feature in Apple's speech implementation - is the missing/seemingly obvious "Start Speaking.. form here" command. In essence..

> _START_ speaking WITH the selected text... DON'T JUST _read_ the selected text!

I was hoping `Dictater` would would make this simple dream possible, but no.  Either it is not as obvious to everyone else, or it is impossible to implement, or something?  I'm hoping the creators of this software have similar sentiments, and will cnsider such an enhancement.

**Comment by SmilinBrian** [comment]
I guess "seemingly obvious" depends on your perspective. As you've written it, I really don't understand what the difference is.

Is the "speaking" supposed to continue reading beyond the selection range? That is, if I select the third paragraph in a long essay, is this functionality to "start speaking the third paragraph and continue until the end of the document"? (Versus the current "speak only the third paragraph since that is what is selected")

**Comment by mralexgray** [comment]
Yes, exactly...  It seems obvious (to me) - from an accessibility standpoint, but sigh, I guess not.

**Comment by SmilinBrian** [comment]
In that case I think Apple will have to address this. Dictater is built as a text service. As a text service within OS X, it can do operations on the selected text (only).

That is, text services have no access to the document as a whole, only to whatever portion (the selection) is sent to them.

**Comment by Nosrac** [comment]
@SmilinBrian is correct.  Dictater only has access to the text you're selecting.
